export {
  OracleSpecError,
  evaluateOracle,
  type AllOracleSpec,
  type AnyOracleSpec,
  type ExitCodeEqualsOracleSpec,
  type FileJsonPointerEqualsOracleSpec,
  type NotOracleSpec,
  type OracleAssertion,
  type OracleEvaluation,
  type OracleObservation,
  type OracleOutcome,
  type OracleProcessObservation,
  type OracleSpec,
  type ProcessStatus,
  type StdoutCapture,
  type StdoutJsonPointerEqualsOracleSpec,
} from './evaluate.js';

export {
  JsonPointerError,
  StrictJsonError,
  assertJsonValue,
  canonicalizeJson,
  jsonDeepEqual,
  parseStrictJson,
  resolveJsonPointer,
  validateJsonPointer,
  type JsonArray,
  type JsonObject,
  type JsonPointerFound,
  type JsonPointerMissing,
  type JsonPointerResult,
  type JsonPrimitive,
  type JsonValue,
} from './json-pointer.js';
